//
export const SET_LOADING_MODAL_AUTHENICATION = "SET_LOADING_MODAL_AUTHENICATION";
//
export const OPEN_LOGIN_WITH_ACCOUNT = "OPEN_LOGIN_WITH_ACCOUNT";
//
export const OPEN_LOGIN_WITH_QR_CODE = "OPEN_LOGIN_WITH_QR_CODE";
//
export const BACK_MAIN_AUTHENICATION = "BACK_MAIN_AUTHENICATION";
//
export const OPEN_MODAL_REGISTER = "OPEN_MODAL_REGISTER";
//
export const OPEN_MODAL_LOGIN = "OPEN_MODAL_LOGIN";
//
export const OPEN_SIGN_IN_WITH_ACCOUNT = "OPEN_SIGN_IN_WITH_ACCOUNT";
//